"use client";

import { useState } from "react";

const Icon = ({ name }: { name: "spark" | "arrow" | "check" | "calendar" | "dots" }) => {
  const paths = {
    spark: "m12 2 1.8 6.2L20 10l-6.2 1.8L12 18l-1.8-6.2L4 10l6.2-1.8L12 2ZM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8L19 16Z",
    arrow: "m9 18 6-6-6-6", check: "m5 12 4 4L19 6", calendar: "M7 3v3M17 3v3M4 9h16M5 5h14v16H5z", dots: "M5 12h.01M12 12h.01M19 12h.01",
  };
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
};

const chartByMode = {
  امروز: { actual: "M4 119 C26 109, 37 91, 58 95 S93 67, 115 75 S149 49, 172 52 S204 25, 230 36 S262 23, 286 17", plan: "M4 125 C30 112, 46 101, 63 88 S96 77, 116 70 S151 60, 174 51 S205 43, 230 30 S258 23, 286 13", label: "۷۲٪ پیشرفت هم‌راستا" },
  هفته: { actual: "M4 125 C25 109, 45 101, 63 87 S92 89, 113 66 S147 60, 169 48 S204 53, 228 34 S262 23, 286 17", plan: "M4 129 C25 117, 45 105, 63 96 S95 77, 113 70 S146 59, 169 50 S203 40, 228 28 S260 20, 286 10", label: "۶۱٪ پیشرفت هم‌راستا" },
  ماه: { actual: "M4 128 C31 119, 44 105, 63 106 S91 83, 113 91 S145 62, 170 65 S203 39, 228 47 S261 25, 286 22", plan: "M4 131 C28 119, 46 109, 64 98 S92 87, 114 78 S146 66, 170 57 S202 43, 228 32 S260 17, 286 8", label: "۵۸٪ پیشرفت هم‌راستا" },
};

export function CoolOverview() {
  const [mode, setMode] = useState<keyof typeof chartByMode>("امروز");
  const [done, setDone] = useState<string[]>(["بازدید کارگاه صفه"]);
  const [notice, setNotice] = useState(false);
  const data = chartByMode[mode];
  const tasks = ["بازدید کارگاه صفه", "تأیید نقشه‌های سازه", "جلسه با سرمایه‌گذار پروژه نور"];
  const toggleTask = (task: string) => setDone((items) => items.includes(task) ? items.filter((item) => item !== task) : [...items, task]);
  const nudge = () => { setNotice(true); window.setTimeout(() => setNotice(false), 3000); };
  return <section className="ad-command-center">
    <header className="ad-command-header"><div><span className="ad-command-kicker"><i />اتاق فرمان کنزا</span><h1>صبح بخیر، آقای کیانی</h1><p>نبض پروژه‌ها آرام است؛ فقط <b>۲ تصمیم</b> برای حفظ ریتم این هفته نیاز به توجه شما دارند.</p></div><div className="ad-command-actions"><div className="ad-command-tabs">{(["امروز", "هفته", "ماه"] as const).map((item) => <button key={item} className={mode === item ? "is-active" : ""} onClick={() => setMode(item)}>{item}</button>)}</div><button className="ad-command-button" onClick={nudge}><Icon name="spark" />مرور هوشمند</button></div></header>
    <div className="ad-command-hero ad-stagger"><div className="ad-command-copy"><span>برد اجرایی · {mode}</span><h2>۸۷٪ پروژه‌ها<br />در ریتم برنامه‌اند</h2><p>چهار پروژه در مسیر برنامه حرکت می‌کنند و یک پروژه برای تصمیم سازه‌ای در صف شماست.</p><button onClick={nudge}>مشاهده‌ی اولویت‌ها <Icon name="arrow" /></button></div><div className="ad-orbit" aria-label="پروژه‌های فعال کنزا"><div className="ad-orbit-ring ad-orbit-ring-one" /><div className="ad-orbit-ring ad-orbit-ring-two" /><div className="ad-orbit-core"><b>۱۲</b><span>پروژه‌ی زنده</span></div><i className="ad-orbit-dot ad-dot-one" /><i className="ad-orbit-dot ad-dot-two" /><i className="ad-orbit-dot ad-dot-three" /></div><div className="ad-hero-metrics"><div><span>جریان نقدی</span><strong>۱۲٫۸ <small>میلیارد</small></strong><b>+۱۸٫۴٪</b></div><div><span>میانگین پیشرفت</span><strong>۶۱ <small>درصد</small></strong><b>+۷٫۲٪</b></div></div></div>
    <div className="ad-command-grid"><article className="ad-card ad-priority-card ad-stagger"><div className="ad-command-card-head"><div><span className="ad-card-kicker">اولویت‌های امروز</span><h2>روی چه چیزی تمرکز کنیم؟</h2></div><button aria-label="گزینه‌ها"><Icon name="dots" /></button></div><div className="ad-task-list">{tasks.map((task, index) => <button key={task} className={done.includes(task) ? "is-done" : ""} onClick={() => toggleTask(task)}><span>{done.includes(task) ? <Icon name="check" /> : `۰${index + 1}`}</span><div><strong>{task}</strong><small>{index === 0 ? "ساعت ۱۱:۳۰" : index === 1 ? "مجموعه صفه · فوریت متوسط" : "ساعت ۱۶:۰۰"}</small></div><Icon name="arrow" /></button>)}</div><button className="ad-text-button" onClick={nudge}>نمایش همه‌ی برنامه‌ها <Icon name="arrow" /></button></article><article className="ad-card ad-signal-card ad-stagger"><div className="ad-command-card-head"><div><span className="ad-card-kicker">سیگنال‌های کسب‌وکار</span><h2>جایی برای تصمیم</h2></div><span className="ad-live-dot">زنده</span></div><div className="ad-signal-main"><span>ارزش فرصت‌های جدید</span><strong>۲۴۶ <small>میلیارد تومان</small></strong><b>۳۶٪ نرخ تبدیل</b></div><div className="ad-signal-line"><i /><i /><i /><i /><i className="is-current" /><i /><i /></div><div className="ad-signal-foot"><span>هفته‌ی پیش</span><strong>امروز</strong><span>هفته‌ی بعد</span></div></article><article className="ad-card ad-project-pulse ad-stagger"><div className="ad-command-card-head"><div><span className="ad-card-kicker">پالس پروژه‌ها</span><h2>نمای سریع کارگاه</h2></div><button className="ad-text-button" onClick={nudge}>جزئیات <Icon name="arrow" /></button></div><div className="ad-pulse-list">{[["رزیدنس چهارباغ", 72, "طبق برنامه"], ["مجموعه صفه", 48, "نیازمند بررسی"], ["خانه جلفا", 89, "طبق برنامه"]].map(([name, progress, state]) => <div key={name as string}><div><strong>{name}</strong><span className={`ad-status ${state === "طبق برنامه" ? "is-good" : "is-alert"}`}>{state}</span></div><p><i><b style={{ width: `${progress}%` }} /></i><em>{progress}٪</em></p></div>)}</div></article></div>
    <section className="ad-analytics-grid">
      <article className="ad-card ad-trajectory-card ad-stagger"><div className="ad-command-card-head"><div><span className="ad-card-kicker">آهنگ اجرا</span><h2>واقعی در برابر برنامه</h2></div><div className="ad-trajectory-legend"><span><i />واقعی</span><span><i />برنامه</span></div></div><div className="ad-trajectory-value"><strong>{data.label}</strong><span>نقطه‌ی پایان امروز</span></div><svg className="ad-trajectory-svg" viewBox="0 0 290 150" preserveAspectRatio="none" aria-label="نمودار پیشرفت اجرایی"><defs><linearGradient id="trajectoryFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#c49065" stopOpacity=".32" /><stop offset="1" stopColor="#c49065" stopOpacity="0" /></linearGradient></defs><g className="ad-chart-gridlines"><path d="M0 28H290M0 68H290M0 108H290M0 148H290" /></g><path className="ad-trajectory-area" d={`${data.actual} L286 150 L4 150 Z`} /><path className="ad-trajectory-plan" d={data.plan} /><path className="ad-trajectory-actual" d={data.actual} /><circle cx="286" cy={mode === "امروز" ? "17" : mode === "هفته" ? "17" : "22"} r="4" /></svg><div className="ad-trajectory-axis"><span>شنبه</span><span>یکشنبه</span><span>دوشنبه</span><span>سه‌شنبه</span><span>امروز</span></div></article>
      <article className="ad-card ad-mix-card ad-stagger"><div className="ad-command-card-head"><div><span className="ad-card-kicker">ترکیب درآمد</span><h2>منابع ارزش جاری</h2></div><button onClick={nudge}><Icon name="dots" /></button></div><div className="ad-mix-visual"><div className="ad-mix-donut"><div><strong>۱۲٫۸</strong><span>میلیارد تومان</span></div></div><ul><li><i className="is-copper" /><span>پروژه‌های مسکونی</span><b>۴۸٪</b></li><li><i className="is-dark" /><span>تجاری ـ اداری</span><b>۳۱٪</b></li><li><i className="is-pale" /><span>بازآفرینی</span><b>۲۱٪</b></li></ul></div></article>
      <article className="ad-card ad-heat-card ad-stagger"><div className="ad-command-card-head"><div><span className="ad-card-kicker">شدت فعالیت</span><h2>هیت‌مپ هفتگی تیم</h2></div><span className="ad-heat-total">۳۸ اقدام</span></div><div className="ad-heat-map">{[1, 2, 3, 4, 5, 6, 7].map((day) => <div key={day}><span>{["ش", "ی", "د", "س", "چ", "پ", "ج"][day - 1]}</span><i className={`l${(day % 4) + 1}`} /><i className={`l${((day + 2) % 4) + 1}`} /><i className={`l${((day + 1) % 4) + 1}`} /><i className={`l${(day % 3) + 1}`} /></div>)}</div><div className="ad-heat-foot"><span>کم‌تر</span><i /><i /><i /><i /><span>بیش‌تر</span></div></article>
    </section>
    <section className="ad-card ad-command-bottom ad-stagger"><div><span className="ad-card-kicker">تقویم نزدیک</span><h2>سه اتفاق پیش رو</h2></div><div className="ad-command-events"><button onClick={nudge}><i className="is-copper" /><span>امروز</span><strong>بازدید رزیدنس چهارباغ</strong><small>۱۱:۳۰</small></button><button onClick={nudge}><i className="is-dark" /><span>فردا</span><strong>تحویل مصالح نما</strong><small>۰۹:۰۰</small></button><button onClick={nudge}><i className="is-green" /><span>پنج‌شنبه</span><strong>جلسه‌ی مالی پروژه نور</strong><small>۱۶:۰۰</small></button></div><button className="ad-command-calendar" onClick={nudge}><Icon name="calendar" />تقویم کامل</button></section>
    {notice && <div className="ad-demo-toast" role="status"><Icon name="check" />مرور هوشمند آماده شد؛ این یک تعامل دموی محلی است.</div>}
  </section>;
}
